services:
  minio:
    image: minio/minio
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 9000:9000
      - 9002:9001

  scylladb:
    image: scylladb/scylla:latest
    command: --alternator-port=8000 --alternator-write-isolation=always
    ports:
      - 9042:9042
      - 9043:8000
    volumes:
      - scylladb-data:/var/lib/scylla
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 5s
      retries: 120
      timeout: 1s  

volumes:
  scylladb-data:
    driver: local 
  minio-data:
    driver: local
